name: 'Bump SemVer without default'
description: 'Bump and push semantic version and create a git tag'
author: 'Dario Blanco Iturriaga and Alexis Jasso'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  npm:
    description: 'Update version in package.json file'
    required: false
    default: 'false'
  packageJsonPath:
    description: 'Specify package.json path'
    required: false
    default: 'package.json'
  prefix:
    description: 'The prefix for the tag'
    required: false
    default: ''
  token:
    description: 'The Github Token to be used to authenticate with Github'
    required: true
outputs:
  tag:
    description: 'The latest tag after running this action'
  version:
    description: 'The semantic version without any "v" or other prefixes'
  bumped:
    description: 'Set to "true" if the version was bumped, otherwise "false"'
branding:
  icon: 'git-merge'
  color: 'purple'
