name: 'Github Tag Bump'
description: 'Bump and push git tag on merge'
author: 'MindDoc Health GmbH'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  defaultBump:
    description: 'The semantic versioning bump (major, minor or patch)'
    required: false
    default: 'patch'
  prefix:
    description: 'The prefix for the tag'
    required: false
    default: ''
  token:
    description: 'The Github Token to be used to authenticate with Github'
    required: true
  withV:
    description: ''
    required: false
    default: 'true'
outputs:
  tag:
    description: 'The latest tag after running this action'
  version:
    description: 'The semantic version without any "v" or other prefixes'
branding:
  icon: 'git-merge'
  color: 'purple'
