name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: minddocdev/github-tag-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
